In [14]:
import numpy as np
import seaborn as sbn
import matplotlib.pyplot as plt

In [15]:
x1 = [1,1,1,1,1,1]
x2 = [-1,-1,-1,-1,-1,-1]
x3 = [-1,-1,1,1,-1,-1]
x4 = [1,1,-1,-1,1,1]
X = np.array([x1,x2,x3,x4])

y1 = [1,1,1]
y2 = [-1,-1,-1]
y3 = [-1,1,-1]
y4 = [1,-1,1]
Y = np.array([y1,y2,y3,y4])
print(X, Y)

[[ 1  1  1  1  1  1]
 [-1 -1 -1 -1 -1 -1]
 [-1 -1  1  1 -1 -1]
 [ 1  1 -1 -1  1  1]] [[ 1  1  1]
 [-1 -1 -1]
 [-1  1 -1]
 [ 1 -1  1]]


In [16]:
def cal_weights(x, y):
    return  np.dot(x.T, y)

weights = cal_weights(X,Y)
weights

array([[4, 0, 4],
       [4, 0, 4],
       [0, 4, 0],
       [0, 4, 0],
       [4, 0, 4],
       [4, 0, 4]])

In [17]:
def forwardbinarytest(matrix):
    matrix[matrix>1]= 1
    matrix[matrix<=0]= -1
    return np.array(matrix)

def backwardbinarytest(matrix):
    matrix[matrix > 1] = 1
    matrix[matrix <=0] = -1
    return np.array(matrix)

In [18]:
def forward(y, weights):
    x = np.dot(y, weights.T)
    return forwardbinarytest(x)

def backward(x, weights):
    y = np.dot(x, weights)
    return backwardbinarytest(y)

In [19]:
print("actual X : ", X)
print("predicted X: ", forward(Y, weights))

actual X :  [[ 1  1  1  1  1  1]
 [-1 -1 -1 -1 -1 -1]
 [-1 -1  1  1 -1 -1]
 [ 1  1 -1 -1  1  1]]
predicted X:  [[ 1  1  1  1  1  1]
 [-1 -1 -1 -1 -1 -1]
 [-1 -1  1  1 -1 -1]
 [ 1  1 -1 -1  1  1]]


In [20]:
print("actual Y: ", Y)
print("predicted Y: ", backward(X, weights))

actual Y:  [[ 1  1  1]
 [-1 -1 -1]
 [-1  1 -1]
 [ 1 -1  1]]
predicted Y:  [[ 1  1  1]
 [-1 -1 -1]
 [-1  1 -1]
 [ 1 -1  1]]
